version: '3.9'
services:
  uas:
    build: .
    container_name: sip_uas
    environment:
      - RUST_LOG=info
      - SIP_BIND_IP=0.0.0.0
      - SIP_PORT=5060
      - RTP_PORT=40000
      - LOCAL_IP=127.0.0.1
    ports:
      - "5060:5060/udp"
      - "40000:40000/udp"
